name: iOS App Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * *'  # Daily run at midnight UTC

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        ios-version: ['16.0', '17.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        npm install -g appium
        npm install -g appium-doctor

    - name: Start Appium Server
      run: |
        appium &
        sleep 5  # Wait for server to start

    - name: Run Tests
      run: |
        python -m pytest test_paywall.py test_home.py --html=report.html

    - name: Upload Test Report
      if: always()  # Run even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-report-${{ matrix.python-version }}-ios${{ matrix.ios-version }}
        path: |
          report.html
          reports/ 